[package]
name = "sel4-simple-task-rpc"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
postcard = ["dep:serde", "dep:postcard"]

[dependencies]
postcard = { version = "1.0.2", default-features = false, features = [], optional = true }
sel4 = { path = "../../../../sel4" }
serde = { version = "1.0.147", default-features = false, features = [], optional = true }
