#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[package]
name = "sel4-capdl-initializer-add-spec"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
anyhow = "1.0.66"
clap = "4.4.6"
fallible-iterator = "0.2.0"
num = "0.4.1"
object = { version = "0.32.1", features = ["all"] }
postcard = { version = "1.0.2", default-features = false, features = ["alloc"] }
sel4-capdl-initializer-types = { path = "../types", features = ["std", "serde", "deflate"] }
sel4-render-elf-with-data = { path = "../../sel4-render-elf-with-data" }
serde_json = "1.0.87"
