[package]
name = "sel4-backtrace-embedded-debug-info-cli"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
clap = "3.2.23"
num = "0.4.1"
sel4-render-elf-with-data = { path = "../../../sel4-render-elf-with-data" }
