[package]
name = "sel4"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "MIT"

[features]
default = ["state"]
single-threaded = []
state = []

[dependencies]
cfg-if = "*"
sel4-config = { path = "./config" }
sel4-sys = { path = "./sys" }
