[package]
name = "sel4-async-block-io-cpiofs"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
futures = { version = "0.3.28", default-features = false, features = ["alloc"] }
hex = { version = "0.4.3", default-features = false }
log = "0.4.17"
lru = "0.10.0"
sel4-async-block-io = { path = ".." }
zerocopy = "0.6.1"
