[package]
name = "sel4-sys-wrappers"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[lib]
crate-type = ["staticlib"]

[dependencies]
sel4-sys = { path = "..", features = ["wrappers"] }
