[package]
name = "sel4cp-http-server-example-virtio-hal-impl"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
log = "0.4.17"
sel4-bounce-buffer-allocator = { path = "../../../../../sel4-bounce-buffer-allocator" }
sel4-externally-shared = { path = "../../../../../sel4-externally-shared" }
sel4-immediate-sync-once-cell = { path = "../../../../../sel4-immediate-sync-once-cell" }
sel4-sync = { path = "../../../../../sel4-sync" }
virtio-drivers = { version = "0.5.0", default-features = false, features = [] }
