[package]
name = "capdl-initializer-with-embedded-spec-embedded-spec-validate"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
deflate = ["capdl-initializer-with-embedded-spec-embedded-spec/deflate"]

[dependencies]
capdl-initializer-types = { path = "../../../types" }
capdl-initializer-with-embedded-spec-build-env = { path = "../../build-env" }
capdl-initializer-with-embedded-spec-embedded-spec = { path = ".." }
