[package]
name = "sel4-dlmalloc"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
dlmalloc = "0.2.3"
sel4-sync = { path = "../sel4-sync" }
