[package]
name = "sel4-embed-debug-info"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
clap = "3.2.23"
render-elf-with-data = { path = "../../../../../build-tools/render-elf-with-data" }
