[package]
name = "sel4-panicking"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
alloc = []

[dependencies]
cfg-if = "*"
sel4-immediate-sync-once-cell = { path = "../sel4-immediate-sync-once-cell" }
sel4-panicking-env = { path = "./env" }

[dependencies.unwinding]
version = "0.1.6"
default-features = false
features = ["unwinder", "fde-custom", "hide-trace", "personality"]
optional = true
