[package]
name = "sel4-loader-add-payload"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
anyhow = "1.0.66"
clap = "3.2.23"
fallible-iterator = "0.2.0"
heapless = "0.7.16"
object = { version = "0.31.0", features = ["all"] }
postcard = { version = "1.0.2", default-features = false, features = ["alloc"] }
sel4-loader-config-types = { path = "../config-types" }
sel4-loader-payload-types = { path = "../payload-types", features = ["serde"] }
sel4-render-elf-with-data = { path = "../../build-tools/sel4-render-elf-with-data" }
serde = { version = "1.0.147", default-features = false, features = ["alloc", "derive"] }
serde_json = "1.0.87"
serde_yaml = "0.9.14"
