[package]
name = "sel4-sync"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
sel4 = { path = "../../sel4" }
sel4-immediate-sync-once-cell = { path = "../sel4-immediate-sync-once-cell" }
